name: Java CI

on:
  push:
    paths-ignore:
    - 'README.md'

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out library
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'

    - name: Cache Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.OS }}-build-${{ hashFiles('**/pom.xml') }}

    - name: Build with Maven
      run: |
        env | grep -E 'M3|M2|MAVEN'
        mvn --version
        unset M2_HOME
        mvn compile

    - name: Test with Maven
      run: mvn test
