name: Java CI

on:
  push:
    paths-ignore:
    - 'README.md'

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out library
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21

    - name: Build with Maven
      run: |
        env | grep -E 'M3|M2|MAVEN'
        mvn --version
        unset M2_HOME
        mvn compile

    # TODO implement api responses and mock client
    #- name: Test with Maven
      #run: mvn test
